steps:
# - name: node:latest
#   entrypoint: yarn
#   args: ["install"]
# - name: node:latest
#   entrypoint: yarn
#   args: ["test"]
# - name: node:latest
#   entrypoint: yarn
#   args: ["build"]
- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "build",
      "-t",
      "gcr.io/$PROJECT_ID/sirvo-app:latest",
      "--cache-from",
      "gcr.io/$PROJECT_ID/sirvo-app:latest",
      ".",
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sirvo-app']
images: ["gcr.io/sirvo-app/sirvo-app"]
