apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sirvo-deployment
  labels:
    name: sirvo-app
    version: 0.0.1
spec:
  replica: 1
  selector:
    matchLabels:
      name: sirvo-app
  template:
    spec:
      containers:
        - name: sirvo-container
          image: gcr.io/sirvo-app/sirvo-app