apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sirvo-deployment
  labels:
    name: sirvo-app
    version: 0.0.4
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sirvo-app
  template:
    metadata:
      name: sirvo-app
      labels:
        name: sirvo-app
    spec:
      containers:
        - name: sirvo-container
          image: gcr.io/sirvo-app/sirvo-app